In [3]:
import random
import matplotlib.pyplot as plt
import numpy as np
 

a = np.zeros((50,3), dtype=np.float64)

def vetorale (a):
  vetor=[]
  for i in range(50):
    for j in range(3):
       a[i,j]=random.uniform(-10,10)
  return(a)

b = np.zeros((50,3), dtype=np.float64)

def sistem(b): 
  for i in range(50):
    x1=a[i,0]
    x2=a[i,1]
    x3=a[i,2]

    c= 3*x1 + 2*x2 + 4*x3 
    d= x1  + x2 + 2*x3  
    e= 4*x1 + 3*x2 + 2*x3

    b[i,0]=c
    b[i,1]=d
    b[i,2]=e
  return (b)


"""
abs((c-y)/c)*100
c= valor esperado
y= valor obtido
c=valor esperado
"""

def aproxim(b):
    matr=np.zeros((50,3))
        
    for i in range(50):
        c=b[i,0]
        d=b[i,1]
        e=b[i,2]

        X1=abs((1-c)/1)*100
        X2=abs((2-d)/2)*100
        X3=abs((3-e)/3)*100

        matr[i,0]=X1
        matr[i,1]=X2
        matr[i,2]=X3
    return(matr)

def media (m):
    matr1=np.zeros((50,1))
    for i in range(50):
        x1=m[i,0]
        x2=m[i,1]
        x3=m[i,2]

        N=(x1+x2+x3)/3

        matr1[i,0]=N
        
    return(matr1)


print(vetorale(a))
print("\n\n\n",sistem(b))
print("\n\n\n", aproxim(b))
print("\n\n\n", media(aproxim(b)))

[[-4.98049859  4.25041814  1.82113567]
 [ 4.97596689 -3.76205676  3.16148864]
 [-3.48253079 -2.60386928 -0.64019707]
 [-7.53317576  9.35963596  3.45556396]
 [-2.27740702  1.58014357 -3.37478223]
 [-8.42503844  1.30970069 -3.80244324]
 [-6.50176823 -4.16936967  4.93260597]
 [ 6.49674522  3.40179077 -5.46225895]
 [ 2.00817699  1.38658879  6.3139845 ]
 [ 7.76480486 -6.4001211  -0.58324887]
 [-3.98060957  9.26348048  4.49295041]
 [-5.49654104  7.51299312  4.07750329]
 [ 1.37132508  2.22934419  3.02516142]
 [ 5.69077917  8.20502598  8.38719499]
 [ 3.32660774 -8.50337843  3.13281413]
 [ 8.2228616  -4.45067204  7.34658071]
 [ 9.1142621  -4.16149126  2.27351033]
 [ 3.55548913  9.11527501 -3.31564349]
 [ 0.61587822  5.26796594  8.7049498 ]
 [-5.39691399 -2.18269816 -9.85300372]
 [ 8.47786937  8.88377718  1.75284331]
 [-4.07348029 -6.06666406 -4.90227489]
 [-4.78531639 -6.63743458 -6.58998739]
 [ 5.33361006  3.71045422  0.46368738]
 [-3.83625274  0.15008979 -1.72909959]
 [ 5.25860801 -3.48799386